---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: next-gen-ui-react
  title: Next Gen UI Patternfly React Renderer
  namespace: uxe
  description: "This npm package provides a collection of reusable Patternfly React components to support dynamic UI rendering for Next Gen UI Agent."
  annotations:
    npm/package: '@rhngui/patternfly-react-renderer'
    npm/registry: npmjs
  tags:
    - "next-gen-ui"
    - "next-gen-ui-agent"
    - "ui"
    - "ux"
    - "ai"
    - "react"
    - "javascript"
    - "typescript"
    - "nodejs"
    - "vite"
    - "eslint"
    - "patternfly"
    - "library"
    - "components"
    - "npm"
spec:
  owner: group:redhat/next-gen-ui
  lifecycle: Implementing
  type: library
  system: uxe/next-gen-ui-agent
